services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - 9042:9042
    volumes:
      - type: bind
        source: ../data_import/csvs
        target: /csvs
    command: '--overprovisioned 1'
